// <auto-generated />
using System;
using CasePilot.Api.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasePilot.Api.Migrations
{
    [DbContext(typeof(CasePilotDbContext))]
    [Migration("20260515130259_AddJwtAuthSupport")]
    partial class AddJwtAuthSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CasePilot.Api.Models.AppPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Name = "cases.view"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Name = "cases.create"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Name = "cases.edit"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Name = "cases.delete"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Name = "docs.view"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Name = "docs.create"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Name = "docs.edit"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Name = "docs.delete"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000009"),
                            Name = "stats.view"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000010"),
                            Name = "users.manage"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000011"),
                            Name = "audit.view"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000012"),
                            Name = "simulator.control"
                        });
                });

            modelBuilder.Entity("CasePilot.Api.Models.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("CasePilot.Api.Models.AppRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("c0000000-0000-0000-0000-000000000009")
                        });
                });

            modelBuilder.Entity("CasePilot.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@casepilot.com",
                            FullName = "Administrator",
                            IsActive = true,
                            Password = "admin123",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "avocat@casepilot.com",
                            FullName = "Ion Popescu",
                            IsActive = true,
                            Password = "avocat123",
                            PasswordHash = ""
                        });
                });

            modelBuilder.Entity("CasePilot.Api.Models.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            UserId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            RoleId = new Guid("a2222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("CasePilot.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CasePilot.Api.Models.CaseDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LegalCaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("CaseDocuments");
                });

            modelBuilder.Entity("CasePilot.Api.Models.DocumentActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocumentActivities");
                });

            modelBuilder.Entity("CasePilot.Api.Models.HearingTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourtRoom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LegalCaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("HearingTerms");
                });

            modelBuilder.Entity("CasePilot.Api.Models.LegalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Court")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reclamant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("LegalCases");
                });

            modelBuilder.Entity("CasePilot.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CasePilot.Api.Models.SuspiciousUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeverityScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SuspiciousUsers");
                });

            modelBuilder.Entity("CasePilot.Api.Models.AppRolePermission", b =>
                {
                    b.HasOne("CasePilot.Api.Models.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasePilot.Api.Models.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CasePilot.Api.Models.AppUserRole", b =>
                {
                    b.HasOne("CasePilot.Api.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasePilot.Api.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CasePilot.Api.Models.AuditLog", b =>
                {
                    b.HasOne("CasePilot.Api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CasePilot.Api.Models.CaseDocument", b =>
                {
                    b.HasOne("CasePilot.Api.Models.LegalCase", "LegalCase")
                        .WithMany("Documents")
                        .HasForeignKey("LegalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalCase");
                });

            modelBuilder.Entity("CasePilot.Api.Models.HearingTerm", b =>
                {
                    b.HasOne("CasePilot.Api.Models.LegalCase", "LegalCase")
                        .WithMany("Hearings")
                        .HasForeignKey("LegalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalCase");
                });

            modelBuilder.Entity("CasePilot.Api.Models.LegalCase", b =>
                {
                    b.HasOne("CasePilot.Api.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CasePilot.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("CasePilot.Api.Models.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CasePilot.Api.Models.SuspiciousUser", b =>
                {
                    b.HasOne("CasePilot.Api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CasePilot.Api.Models.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CasePilot.Api.Models.AppRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CasePilot.Api.Models.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CasePilot.Api.Models.LegalCase", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Hearings");
                });
#pragma warning restore 612, 618
        }
    }
}
